spring.application.name=fatecads

# Configuração do banco de dados H2
spring.datasource.url=jdbc:h2:mem:fatecads_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar console H2
spring.h2.console.enabled=true

#Atualização automática do banco de dados
spring.jpa.hibernate.ddl-auto=create-drop

# Mostrar as consultas SQL no console
spring.jpa.show-sql=true

#Configurar dialect do H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#Não formaatar as consultas SQL
spring.jpa.properties.hibernate.format_sql=false

#Configuração da porta do servidor
server.port=8081